## Web Scrapping Available for sale Bikes in India

In [6]:
##Imports 
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from time import sleep
import pandas as pd
import numpy as np

In [ ]:
!pip3 install  selenium

### Driver setup

In [3]:
try:
    # Initialize the browser
    driver = webdriver.Chrome()

    # Navigate to the URL
    driver.get('https://www.bikedekho.com')

    # Find the search text input element
    search_text_input = driver.find_element(By.ID, 'cardekhosearchtext')

    # Example usage:
    search_query = "TVS Bikes"  # Example search query
    search_text_input.send_keys(search_query)  # Input the search query into the search text input

    # Wait for a while to let the dropdown options appear
    sleep(2)

    # Re-find the dropdown options after waiting
    dropdown_option_xpath = '//*[@id="rf01"]/header/div[1]/div/div/div[2]/div/div/form/div/div/div/ul/li'
    dropdown_options = driver.find_elements(By.XPATH, dropdown_option_xpath)

    # Select the first option from the dropdown if available
    if dropdown_options:
        first_option = dropdown_options[0]
        first_option.click()

    sleep(2)

    bike_list_element = driver.find_element(By.CLASS_NAME, 'bikelist')

    # Extract data from the bike list
    for index in range(7):  # Iterate through each item, skipping the 5th and 6th items
        if index == 5 or index == 6:
            continue
        
        bike_items = bike_list_element.find_elements(By.TAG_NAME, 'li')
    # for index,item in enumerate(bike_items):

    #     if index == 5 or index == 6:
    #         continue
        # Extract data from each item as needed
        bike_name = item.find_element(By.TAG_NAME, 'h3').text
        bike_price = item.find_element(By.CLASS_NAME, 'price').text
        basic_specs = item.find_element(By.CLASS_NAME, 'dotlist').text
        print("Bike Name:", bike_name)
        print("Bike Price:", bike_price)
        print("Basic Specs:", basic_specs)
        print("-" * 50)
       

except Exception as e:
    print("An error occurred:", str(e))

# finally:
#     # Close the browser
#     driver.quit()

An error occurred: name 'item' is not defined

//*[@id="rf01"]/div[1]/div/main/div[1]/div[1]/section[2]/div/a

//*[@id="1480"]/div/div[1]/div[2]/img

driver.find_element(By.ID, '1480')

In [24]:
try:
    # Initialize the browser
    driver = webdriver.Chrome()

    # Navigate to the URL
    driver.get('https://www.bikedekho.com')

    # Example search queries list
    search_queries = ['Hero bike', 'Bajaj bike', 'TVS bike', 'Royal Enfield bike', 'Honda bike', 'Yamaha bike', 'Suzuki bike', 'KTM bike', 'Jawa bike', 'Benelli bike', 'Harley bike', 'Triumph bike', 'Ducati bike', 'BMW bike', 'Kawasaki bike', 'Husqvarna bike', 'Revolt bike', 'Ather bike']
    # search_queries = ['ola bike']

    for search_query in search_queries:
        # Find the search text input element
        search_text_input = driver.find_element(By.ID, 'cardekhosearchtext')

        # Input the search query into the search text input
        search_text_input.clear()  # Clear any previous input
        search_text_input.send_keys(search_query)

        # Wait for a while to let the dropdown options appear
        sleep(2)

        # Re-find the dropdown options after waiting
        dropdown_option_xpath = '//*[@id="rf01"]/header/div[1]/div/div/div[2]/div/div/form/div/div/div/ul/li'
        dropdown_options = driver.find_elements(By.XPATH, dropdown_option_xpath)

        # Select the first option from the dropdown if available
        if dropdown_options:
            first_option = dropdown_options[0]
            first_option.click()

        sleep(2)

        bike_list_element = driver.find_element(By.CLASS_NAME, 'bikelist')

        bike_details =[]

        # Extract data from the bike list
        for index, item in enumerate(bike_list_element.find_elements(By.TAG_NAME, 'li')):
            # Skip list items 6 and 7
            if index == 5 or index == 6:
                continue

            # Extract data from each item as needed
            bike_name = item.find_element(By.TAG_NAME, 'h3').text
            bike_price = item.find_element(By.CLASS_NAME, 'price').text
            basic_specs = item.find_element(By.CLASS_NAME, 'dotlist').text

            bike_df = {'Name': bike_name, 'Price': bike_price, 'Basic Specs': basic_specs}

            bike_details.append(bike_df)
            

        # bike_details = []
        # for item_index, item in enumerate(bike_items):
        #     # Skip list item 6 and 7
        #     if item_index == 5 or item_index == 6:
        #         continue

        #     bike_name = item.find_element(By.TAG_NAME, 'h3').text
        #     bike_price = item.find_element(By.CLASS_NAME, 'price').text
        #     basic_specs = item.find_element(By.CLASS_NAME, 'dotlist').text

        #     bike_details.append({'Name': bike_name, 'Price': bike_price, 'Basic Specs': basic_specs})

        # # Print scraped data for the brand
        # print(f"Scraped data for Brand {index + 1}: {brand_name}")
        
        
        # Save scraped data to a DataFrame
        bikes_df_basics1 = pd.DataFrame(bike_details)
        # bikes_df_basics1.to_csv(f"{bike_name}_bikes.csv", index=False)  # Save data to CSV file
        print(bikes_df_basics1)

except Exception as e:
    print("An error occurred:", str(e))


finally:
    # Close the browser
    driver.quit()

                        Name                 Price  \
0         Hero Splendor Plus   Rs.75,141 - 77,986*
1           Hero Xtreme 125R   Rs.95,000 - 99,500*
2             Hero HF Deluxe   Rs.59,998 - 68,768*
3    Hero Splendor Plus XTEC            Rs.79,911*
4        Hero Super Splendor   Rs.80,848 - 88,328*
5           Hero Mavrick 440  Rs.1.99 - 2.24 Lakh*
6         Hero XPulse 200 4V  Rs.1.46 - 1.53 Lakh*
7               Hero Glamour   Rs.82,348 - 86,348*
8           Hero Xtreme 160R  Rs.1.22 - 1.33 Lakh*
9          Hero Passion XTEC   Rs.81,038 - 85,438*
10        Hero Pleasure Plus   Rs.70,838 - 82,738*
11          Hero Karizma XMR         Rs.1.80 Lakh*
12         Hero Passion Plus            Rs.77,951*
13  Hero Super Splendor XTEC   Rs.85,178 - 89,078*
14         Hero Glamour XTEC   Rs.87,748 - 92,348*
15          Hero Destini 125   Rs.80,048 - 86,538*
16             Hero Xoom 110   Rs.71,484 - 79,967*
17       Hero Xtreme 160R 4V  Rs.1.27 - 1.37 Lakh*
18               Hero HF 100            Rs.59,018*
19       Hero Xtreme 200S 4V         Rs.1.41 Lakh*
20       Hero XPulse 200T 4V         Rs.1.40 Lakh*
21        Hero Destini Prime            Rs.71,499*

                               Basic Specs
0                  80.6 kmpl97.2 cc8.02 PS
1                  66 kmpl124.7 cc11.55 PS
2                    70 kmpl97.2 cc8.02 PS
3                  83.2 kmpl97.2 cc8.02 PS
4                   55 kmpl124.7 cc10.8 PS
5           440 cc27.36 PS36 Nm @ 4000 rpm
6   51.59 kmpl199.6 cc19.17 PS at 8500 rpm
7                    55 kmpl125 cc10.53 PS
8                  55.47 kmpl163 cc15.2 PS
9                   56 kmpl113.2 cc9.15 PS
10                                 50 kmpl
11                 41.55 kmpl210 cc25.5 PS
12                   70 kmpl97.2 cc8.02 PS
13                 68 kmpl124.7 cc10.84 PS
14                 60 kmpl124.7 cc10.84 PS
15                  50 kmpl124.6 cc9.10 PS
16                  45 kmpl110.9 cc8.15 PS
17               48.28 kmpl163.2 cc16.9 PS
18                   70 kmpl97.2 cc8.02 PS
19                  40 kmpl199.6 cc19.1 PS
20                  40 kmpl199.6 cc19.1 PS
21                  56 kmpl124.6 cc9.09 PS
                        Name                 Price  \
0         Bajaj Pulsar NS200         Rs.1.57 Lakh*
1        Bajaj Pulsar NS 125         Rs.1.05 Lakh*
2           Bajaj Pulsar 125   Rs.80,416 - 94,138*
3           Bajaj Pulsar 150  Rs.1.10 - 1.15 Lakh*
4          Bajaj Pulsar N160         Rs.1.31 Lakh*
5         Bajaj Pulsar RS200         Rs.1.72 Lakh*
6         Bajaj Pulsar NS160         Rs.1.46 Lakh*
7         Bajaj Pulsar 220 F         Rs.1.38 Lakh*
8          Bajaj Dominar 400         Rs.2.30 Lakh*
9               Bajaj Chetak  Rs.1.15 - 1.44 Lakh*
10         Bajaj Pulsar N150         Rs.1.18 Lakh*
11         Bajaj Platina 110   Rs.70,400 - 79,821*
12         Bajaj Platina 100            Rs.67,808*
13         Bajaj Dominar 250         Rs.1.84 Lakh*
14         Bajaj Pulsar N250         Rs.1.50 Lakh*
15  Bajaj Avenger Street 160         Rs.1.17 Lakh*
16             Bajaj CT 110X            Rs.69,216*
17         Bajaj Pulsar F250         Rs.1.50 Lakh*
18  Bajaj Avenger Cruise 220         Rs.1.43 Lakh*
19             Bajaj CT 125X   Rs.74,016 - 77,216*
20         Bajaj Pulsar P150  Rs.1.17 - 1.20 Lakh*
21  Bajaj Avenger 220 Street         Rs.1.43 Lakh*

                    Basic Specs
0     40.36 kmpl199.5 cc24.5 PS
1   64.75 kmpl124.45 cc11.99 PS
2     51.46 kmpl124.4 cc11.8 PS
3        47.5 kmpl149.5 cc14 PS
4      59.11 kmpl164.82 cc16 PS
5        35 kmpl199.5 cc24.5 PS
6        52 kmpl160.3 cc17.2 PS
7          40 kmpl220 cc20.4 PS
8          27 kmpl373.3 cc40 PS
9                  4.2 kW4.3 Hr
10      48 kmpl149.68 cc14.5 PS
11       70 kmpl115.45 cc8.6 PS
12          70 kmpl102 cc7.9 PS
13     35.03 kmpl248.77 cc27 PS
14      35 kmpl249.07 cc24.5 PS
15         47.2 kmpl160 cc15 PS
16       70 kmpl115.45 cc8.6 PS
17      35 kmpl249.07 cc24.5 PS
18        40 kmpl220 cc19.03 PS
19     59.6 kmpl124.4 cc10.9 PS
20    49.7 kmpl149.68 cc14.5 PS
21        40 kmpl220 cc19.03 PS
                     Name                   Price                 Basic Specs
0              TVS Raider  Rs.95,219 - 1.03 Lakh*  71.94 kmpl124.8 cc11.38 PS
1      TVS Apache RTR 160    Rs.1.19 - 1.26 Lakh*     47 kmpl159.7 cc16.04 PS
2   TVS Apache RTR 160 4V    Rs.1.24 - 1.45 Lakh*  47.61 kmpl159.7 cc17.55 PS
3           TVS NTORQ 125  Rs.84,636 - 1.05 Lakh*   54.33 kmpl124.8 cc9.38 PS
4               TVS iQube    Rs.1.17 - 1.23 Lakh*                      4.4 kW
5             TVS Jupiter     Rs.73,340 - 89,748*      50 kmpl109.7 cc7.88 PS
6      TVS Apache RTR 310    Rs.2.43 - 2.64 Lakh*    35 kmpl312.12 cc 35.6 PS
7               TVS XL100     Rs.44,999 - 59,695*       80 kmpl99.7 cc4.35 PS
8       TVS Apache RR 310           Rs.2.72 Lakh*     33.1 kmpl312.2 cc 34 PS
9               TVS Ronin    Rs.1.49 - 1.73 Lakh*   42.95 kmpl225.9 cc20.4 PS
10        TVS Jupiter 125     Rs.86,405 - 96,855*   57.27 kmpl124.8 cc8.15 PS
11    TVS Scooty Pep Plus     Rs.65,514 - 68,414*        50 kmpl87.8 cc5.4 PS
12              TVS Sport     Rs.59,431 - 70,773*      70 kmpl109.7 cc8.29 PS
13     TVS Apache RTR 180           Rs.1.32 Lakh*     45 kmpl177.4 cc17.02 PS
14  TVS Apache RTR 200 4V           Rs.1.47 Lakh*    37 kmpl197.75 cc20.82 PS
15             TVS Radeon     Rs.62,405 - 80,744*   73.68 kmpl109.7 cc8.19 PS
16        TVS Scooty Zest     Rs.73,931 - 75,293*      48 kmpl109.7 cc7.81 PS
17     TVS Star City Plus     Rs.78,770 - 81,920*   83.09 kmpl109.7 cc8.19 PS
18                  TVS X           Rs.2.50 Lakh*                    7 kW4 Hr
                               Name                 Price  \
0         Royal Enfield Classic 350  Rs.1.93 - 2.25 Lakh*
1          Royal Enfield Hunter 350  Rs.1.50 - 1.75 Lakh*
2          Royal Enfield Bullet 350  Rs.1.74 - 2.16 Lakh*
3  Royal Enfield Continental GT 650  Rs.3.19 - 3.45 Lakh*
4       Royal Enfield Himalayan 450  Rs.2.85 - 2.98 Lakh*
5          Royal Enfield Meteor 350  Rs.2.03 - 2.30 Lakh*
6    Royal Enfield Super Meteor 650  Rs.3.64 - 3.94 Lakh*
7     Royal Enfield Interceptor 650  Rs.3.03 - 3.31 Lakh*
8         Royal Enfield Shotgun 650  Rs.3.59 - 3.73 Lakh*
9           Royal Enfield Scram 411  Rs.2.06 - 2.12 Lakh*

                   Basic Specs
0  41.55 kmpl349.34 cc20.21 PS
1    36.2 kmpl349.34 cc20.4 PS
2         37 kmpl349 cc20.4 PS
3      27 kmpl647.95 cc47.4 PS
4        30 kmpl452 cc40.02 PS
5      41.88 kmpl349 cc20.4 PS
6           25 kmpl648 cc47 PS
7      25 kmpl647.95 cc47.4 PS
8        22 kmpl648 cc47.65 PS
9     38.23 kmpl411 cc24.31 PS
                          Name                   Price  \
0              Honda Activa 6G     Rs.76,234 - 82,734*
1                 Honda SP 125     Rs.86,017 - 90,567*
2                  Honda Shine     Rs.79,800 - 83,800*
3                    Honda Dio     Rs.70,211 - 77,712*
4             Honda Activa 125     Rs.79,806 - 88,979*
5                Honda Unicorn           Rs.1.10 Lakh*
6            Honda Hness CB350    Rs.2.10 - 2.16 Lakh*
7             Honda Hornet 2.0    Rs.1.39 - 1.40 Lakh*
8                  Honda SP160    Rs.1.18 - 1.22 Lakh*
9              Honda Shine 100              Rs.64,900*
10               Honda Dio 125     Rs.83,400 - 92,300*
11                Honda CB200X           Rs.1.47 Lakh*
12                Honda CB300F           Rs.1.70 Lakh*
13                 Honda CB350       Rs.2 - 2.18 Lakh*
14                  Honda Livo     Rs.78,500 - 82,500*
15                Honda CB300R           Rs.2.40 Lakh*
16               Honda CB350RS    Rs.2.15 - 2.19 Lakh*
17          Honda CD 110 Dream              Rs.73,400*
18             Honda Gold Wing          Rs.39.16 Lakh*
19                 Honda NX500           Rs.5.90 Lakh*
20  Honda CRF1100L Africa Twin  Rs.15.97 - 17.51 Lakh*
21        Honda XL750 Transalp             Rs.11 Lakh*

                    Basic Specs
0       50 kmpl109.51 cc7.84 PS
1      60 kmpl123.94 cc10.87 PS
2      55 kmpl123.94 cc10.74 PS
3       50 kmpl109.51 cc7.85 PS
4          60 kmpl124 cc8.30 PS
5       60 kmpl162.7 cc12.91 PS
6    45.8 kmpl348.36 cc21.07 PS
7    57.35 kmpl184.4 cc17.26 PS
8      65 kmpl162.71 cc13.46 PS
9     55 kmpl98.98 cc7.38 ps PS
10      48 kmpl123.92 cc8.28 PS
11      40 kmpl184.4 cc17.26 PS
12      30 kmpl293.52 cc24.4 PS
13  42.17 kmpl348.36 cc21.07 PS
14      60 kmpl109.51 cc8.79 PS
15     30 kmpl286.01 cc31.13 PS
16     35 kmpl348.36 cc21.07 PS
17      65 kmpl109.51 cc8.79 PS
18       14 kmpl1833 cc126.4 PS
19      27.78 kmpl471 cc47.5 PS
20     20 kmpl1082.96 cc99.2 PS
21         23 kmpl755 cc91.7 PS
                            Name                 Price  \
0                   Yamaha MT 15  Rs.1.68 - 1.73 Lakh*
1                  Yamaha R15 V4  Rs.1.82 - 1.98 Lakh*
2                    Yamaha R15S         Rs.1.65 Lakh*
3               Yamaha FZS-FI V3  Rs.1.22 - 1.23 Lakh*
4     Yamaha RayZR 125 Fi Hybrid   Rs.84,730 - 96,130*
5                Yamaha FZ-FI V3         Rs.1.17 Lakh*
6               Yamaha Aerox 155  Rs.1.47 - 1.49 Lakh*
7   Yamaha Fascino 125 Fi Hybrid   Rs.80,100 - 92,830*
8                    Yamaha FZ X  Rs.1.36 - 1.37 Lakh*
9               Yamaha FZS-FI V4  Rs.1.29 - 1.30 Lakh*
10                  Yamaha MT-03         Rs.4.60 Lakh*
11                     Yamaha R3         Rs.4.65 Lakh*
12                  Yamaha FZ 25         Rs.1.51 Lakh*
13                 Yamaha FZS 25         Rs.1.54 Lakh*

                Basic Specs
0   56.87 kmpl155 cc18.4 PS
1   55.20 kmpl155 cc18.4 PS
2      40 kmpl155 cc18.6 PS
3   49.31 kmpl149 cc12.4 PS
4    71.33 kmpl125 cc8.2 PS
5    49.3 kmpl149 cc12.4 PS
6     48.62 kmpl155 cc15 PS
7    68.75 kmpl125 cc8.2 PS
8      45 kmpl149 cc12.4 PS
9      46 kmpl149 cc12.4 PS
10    26.31 kmpl321 cc42 PS
11       25 kmpl321 cc42 PS
12  50.33 kmpl249 cc20.8 PS
13     40 kmpl249 cc20.8 PS
                    Name                   Price            Basic Specs
0      Suzuki Access 125     Rs.79,900 - 90,500*    45 kmpl124 cc8.7 PS
1        Suzuki Hayabusa          Rs.16.90 Lakh*   17 kmpl1340 cc190 PS
2  Suzuki Burgman Street  Rs.94,000 - 1.14 Lakh*    48 kmpl124 cc8.7 PS
3       Suzuki Gixxer SF    Rs.1.37 - 1.46 Lakh*   45 kmpl155 cc13.6 PS
4          Suzuki Gixxer    Rs.1.35 - 1.46 Lakh*   45 kmpl155 cc13.6 PS
5      Suzuki V-Strom SX           Rs.2.12 Lakh*   32 kmpl249 cc26.5 PS
6   Suzuki Gixxer SF 250    Rs.1.92 - 2.06 Lakh*   38 kmpl249 cc26.5 PS
7          Suzuki Avenis     Rs.92,000 - 92,800*  55 kmpl124.3 cc8.7 PS
8      Suzuki Gixxer 250    Rs.1.81 - 1.98 Lakh*   38 kmpl249 cc26.5 PS
9          Suzuki Katana          Rs.13.61 Lakh*          23 kmpl999 cc
                  Name                 Price                 Basic Specs
0         KTM Duke 390         Rs.3.11 Lakh*     28.9 kmpl398.63 cc46 PS
1         KTM Duke 200         Rs.1.97 Lakh*          33 kmpl200 cc25 PS
2         KTM 125 Duke         Rs.1.79 Lakh*   46.92 kmpl124.7 cc14.5 PS
3         KTM 250 Duke         Rs.2.40 Lakh*    30.08 kmpl249.07 cc30 PS
4           KTM RC 200  Rs.2.18 - 2.18 Lakh*        35 kmpl199.5 cc25 PS
5           KTM RC 390  Rs.3.18 - 3.19 Lakh*  25.89 kmpl373.27 cc43.5 PS
6           KTM RC 125         Rs.1.90 Lakh*      41 kmpl124.7 cc14.5 PS
7    KTM 390 Adventure  Rs.3.39 - 3.61 Lakh*            30 kmpl373.27 cc
8    KTM 250 Adventure         Rs.2.47 Lakh*    38.12 kmpl248.76 cc30 PS
9  KTM 390 Adventure X         Rs.2.81 Lakh*        30 kmpl373 cc43.5 PS
             Name          Price                Basic Specs
0  Jawa 42 Bobber  Rs.2.25 Lakh*   30.56 kmpl334 cc32.74 PS
1         Jawa 42  Rs.1.98 Lakh*      33 kmpl293 cc27.32 PS
2      Jawa Perak  Rs.2.13 Lakh*  34.05 kmpl334 cc30. 64 PS
3        Jawa 350  Rs.2.15 Lakh*      30 kmpl334 cc22.57 PS
                    Name                 Price              Basic Specs
0        Benelli TRK 502  Rs.5.85 - 6.35 Lakh*  30.16 kmpl500 cc47.5 PS
1  Benelli Imperiale 400         Rs.2.35 Lakh*    33.49 kmpl374 cc21 PS
2          Benelli 502 C         Rs.5.25 Lakh*  26.52 kmpl500 cc47.5 PS
3        Benelli TRK 251         Rs.2.89 Lakh*  31.81 kmpl249 cc25.8 PS
4   Benelli Leoncino 500         Rs.4.99 Lakh*     23 kmpl500 cc47.5 PS
                                   Name                   Price  \
0           Harley Davidson Sportster S          Rs.15.54 Lakh*
1                  Harley Davidson X440    Rs.2.40 - 2.80 Lakh*
2           Harley Davidson Fat Boy 114          Rs.24.49 Lakh*
3               Harley Davidson Fat Bob          Rs.20.49 Lakh*
4      Harley Davidson Pan America 1250  Rs.18.25 - 21.24 Lakh*
5             Harley Davidson Nightster  Rs.12.24 - 12.99 Lakh*
6      Harley Davidson Heritage Classic          Rs.26.59 Lakh*
7  Harley Davidson Street Glide Special          Rs.37.49 Lakh*
8    Harley Davidson Road Glide Special          Rs.40.49 Lakh*

                Basic Specs
0  19.6 kmpl1252 cc122.3 PS
1     35 kmpl440 cc27.37 PS
2   18.1 kmpl1868 cc95.1 PS
3   18.1 kmpl1868 cc93.8 PS
4   18.33 kmpl1252 cc152 PS
5    18.1 kmpl975 cc89.7 PS
6   18.1 kmpl1868 cc95.1 PS
7   16.3 kmpl1868 cc93.8 PS
8   16.3 kmpl1868 cc93.8 PS
                              Name                   Price  \
0                Triumph Speed 400           Rs.2.33 Lakh*
1                 Triumph Rocket 3  Rs.19.90 - 21.40 Lakh*
2          Triumph Scrambler 400 X           Rs.2.63 Lakh*
3            Triumph Street Triple  Rs.10.17 - 12.07 Lakh*
4              Triumph Trident 660           Rs.8.12 Lakh*
5        Triumph Bonneville Bobber  Rs.12.05 - 12.85 Lakh*
6               Triumph Tiger 1200  Rs.19.19 - 21.69 Lakh*
7           Triumph Speed Twin 900    Rs.8.49 - 8.79 Lakh*
8                Triumph Tiger 900  Rs.13.70 - 15.50 Lakh*
9          Triumph Bonneville T120  Rs.11.09 - 11.89 Lakh*
10         Triumph Bonneville T100   Rs.9.69 - 10.04 Lakh*
11         Triumph Tiger Sport 660           Rs.9.34 Lakh*
12              Triumph Speed Twin          Rs.11.09 Lakh*
13  Triumph Bonneville Speedmaster  Rs.12.05 - 12.85 Lakh*
14       Triumph Speed Triple 1200          Rs.17.95 Lakh*
15           Triumph Scrambler 900   Rs.9.59 - 10.19 Lakh*
16         Triumph Tiger 850 Sport          Rs.11.95 Lakh*
17        Triumph Scrambler 1200 X  Rs.11.83 - 12.13 Lakh*

                      Basic Specs
0           30 kmpl398.15 cc40 PS
1         14.28 Kmpl2458 cc167 PS
2         28.3 kmpl398.15 cc40 PS
3           19.2 kmpl765 cc130 PS
4           17.47 kmpl660 cc81 PS
5          22.22 Kmpl1200 cc78 PS
6         19.60 Kmpl1160 cc150 PS
7           24.39 Kmpl900 cc65 PS
8         19.23 Kmpl888 cc95.2 PS
9          21.27 kmpl1200 cc80 PS
10          24.39 Kmpl900 cc65 PS
11          22.22 Kmpl660 cc81 PS
12        19.60 Kmpl1200 cc100 PS
13         22.22 Kmpl1200 cc78 PS
14         17.9 kmpl1160 cc180 PS
15           23.2 kmpl900 cc65 PS
16             19 kmpl888 cc85 PS
17  1200 cc90 PS110 Nm @ 4250 rpm
                            Name                   Price  \
0             Ducati Panigale V4  Rs.27.41 - 69.99 Lakh*
1        Ducati Streetfighter V4  Rs.22.15 - 25.69 Lakh*
2           Ducati Scrambler 800     Rs.10.39 - 12 Lakh*
3                 Ducati Monster  Rs.12.95 - 15.95 Lakh*
4               Ducati Diavel V4          Rs.25.91 Lakh*
5             Ducati Panigale V2  Rs.20.27 - 23.60 Lakh*
6          Ducati SuperSport 950  Rs.15.75 - 18.69 Lakh*
7        Ducati Streetfighter V2          Rs.18.10 Lakh*
8             Ducati Diavel 1260  Rs.21.49 - 24.99 Lakh*
9          Ducati Scrambler 1100  Rs.11.95 - 15.99 Lakh*
10         Ducati Multistrada V2  Rs.16.05 - 18.32 Lakh*
11         Ducati Multistrada V4  Rs.21.48 - 31.48 Lakh*
12        Ducati Multistrada 950          Rs.15.49 Lakh*
13        Ducati Hypermotard 950  Rs.15.60 - 17.99 Lakh*
14                Ducati XDiavel  Rs.21.20 - 24.49 Lakh*
15  Ducati Scrambler Desert Sled  Rs.10.99 - 12.59 Lakh*
16                Ducati DesertX          Rs.17.91 Lakh*

                  Basic Specs
0   13.1 kmpl1103 cc218.48 PS
1      13.2 kmpl1103 cc208 PS
2       19 kmpl803 cc74.01 PS
3    18.9 kmpl937 cc112.54 PS
4   18.2 kmpl1158 cc170.33 PS
5    16.6 kmpl955 cc157.15 PS
6       17 kmpl937 cc110.1 PS
7    16.7 kmpl955 cc155.12 PS
8    18.5 kmpl1262 cc164.2 PS
9      20 kmpl1079 cc85.65 PS
10    16.9 kmpl937 cc114.5 PS
11           15.4 kmpl1158 cc
12   22.86 kmpl937 cc114.5 PS
13    19.6 kmpl937 cc114.2 PS
14   18.5 kmpl1262 cc152.2 PS
15     19.6 kmpl803 cc72.8 PS
16   17.8 kmpl937 cc111.52 PS
                         Name                   Price  \
0               BMW S 1000 RR  Rs.20.50 - 24.95 Lakh*
1                BMW G 310 RR           Rs.3.05 Lakh*
2                 BMW G 310 R           Rs.2.90 Lakh*
3                BMW G 310 GS           Rs.3.30 Lakh*
4               BMW R 1250 GS          Rs.20.55 Lakh*
5               BMW M 1000 RR        Rs.49 - 55 Lakh*
6     BMW R 1250 GS Adventure          Rs.22.50 Lakh*
7                BMW C 400 GT          Rs.11.25 Lakh*
8              BMW K 1600 GTL             Rs.33 Lakh*
9                BMW F 850 GS          Rs.12.95 Lakh*
10                BMW F 900 R  Rs.10.80 - 10.95 Lakh*
11     BMW F 850 GS Adventure          Rs.13.75 Lakh*
12               BMW F 900 XR          Rs.12.55 Lakh*
13      BMW R NineT Scrambler          Rs.17.25 Lakh*
14   BMW K 1600 Grand America             Rs.33 Lakh*
15                   BMW R 18  Rs.19.90 - 25.90 Lakh*
16              BMW R 1250 RT          Rs.24.95 Lakh*
17              BMW S 1000 XR          Rs.22.10 Lakh*
18               BMW S 1000 R     Rs.19 - 23.30 Lakh*
19  BMW R 18 Transcontinental          Rs.31.50 Lakh*
20                BMW R nineT        Rs.19 - 24 Lakh*
21               BMW R 1250 R          Rs.16.25 Lakh*
22          BMW K 1600 Bagger          Rs.29.90 Lakh*

                  Basic Specs
0   15.62 Kmpl999 cc212.91 PS
1     30.3 kmpl313 cc33.99 PS
2       32.46 kmpl313 cc34 PS
3       29.26 kmpl313 cc34 PS
4        15 kmpl1254 cc136 PS
5     15.4 kmpl999 cc212.1 PS
6        14 kmpl1254 cc136 PS
7        28.6 kmpl350 cc34 PS
8    16.9 kmpl1649 cc160.4 PS
9     24.4 kmpl853 cc95.17 PS
10    23.8 kmpl895 cc104.6 PS
11      24 kmpl853 cc95.17 PS
12    23.8 kmpl895 cc104.6 PS
13  19.6 kmpl1170 cc108.77 PS
14   16.9 kmpl1649 cc160.4 PS
15   17.8 kmpl1802 cc91.09 PS
16     21 kmpl1254 cc135.9 PS
17        20 kmpl999 cc165 PS
18      16.1 kmpl999 cc165 PS
19  17.24 kmpl1802 cc91.09 PS
20  19.6 kmpl1170 cc108.77 PS
21    21 kmpl1254 cc135.96 PS
22  16.94 Kmpl1649 cc160.4 PS
                     Name                   Price  \
0   Kawasaki Ninja ZX-10R          Rs.16.63 Lakh*
1       Kawasaki Ninja H2          Rs.79.90 Lakh*
2           Kawasaki Z900           Rs.9.29 Lakh*
3      Kawasaki Ninja 300           Rs.3.43 Lakh*
4      Kawasaki Ninja 400           Rs.5.24 Lakh*
5      Kawasaki Ninja 500           Rs.5.24 Lakh*
6    Kawasaki Ninja ZX-6R          Rs.11.09 Lakh*
7     Kawasaki Ninja ZX4R           Rs.8.49 Lakh*
8   Kawasaki Ninja 1000SX          Rs.12.20 Lakh*
9           Kawasaki W175    Rs.1.22 - 1.35 Lakh*
10     Kawasaki Ninja 650           Rs.7.16 Lakh*
11          Kawasaki Z650           Rs.6.65 Lakh*
12    Kawasaki Eliminator           Rs.5.62 Lakh*
13          Kawasaki Z H2  Rs.23.48 - 27.76 Lakh*
14    Kawasaki Versys 650           Rs.7.77 Lakh*
15      Kawasaki Vulcan S           Rs.7.10 Lakh*
16       Kawasaki KLX 140           Rs.4.11 Lakh*
17       Kawasaki KLX 110           Rs.3.12 Lakh*
18        Kawasaki Z650RS           Rs.6.99 Lakh*
19        Kawasaki Z900RS          Rs.16.80 Lakh*
20   Kawasaki Versys 1000          Rs.12.31 Lakh*
21         Kawasaki KX112           Rs.4.88 Lakh*
22        Kawasaki KX 250           Rs.7.99 Lakh*
23        Kawasaki KX 450           Rs.8.59 Lakh*
24      Kawasaki KLX 450R           Rs.8.99 Lakh*
25        Kawasaki KX 100           Rs.4.88 Lakh*
26   Kawasaki W800 Street           Rs.7.33 Lakh*
27      Kawasaki KLX230RS           Rs.5.21 Lakh*
28          Kawasaki KX65           Rs.3.12 Lakh*


In [5]:
import re

# List of bike brands in India
bike_brands_in_india = [
    "Hero MotoCorp",
    "Bajaj Auto",
    "TVS Motor Company",
    "Royal Enfield",
    "Honda Motorcycle and Scooter India (HMSI)",
    "Yamaha Motor India",
    "Suzuki Motorcycle India Private Limited (SMIPL)",
    "KTM India",
    "Mahindra Two Wheelers",
    "Jawa Motorcycles",
    "Benelli India",
    "Harley-Davidson India",
    "Triumph Motorcycles India",
    "Ducati India",
    "BMW Motorrad India",
    "Kawasaki Motors Pvt. Ltd.",
    "Husqvarna Motorcycles India",
    "Revolt Motors",
    "Ather Energy"
]

# Function to add "bike" text after the first word and remove everything after that addition
def add_bike_and_remove_after(lst):
    updated_list = []
    for brand in lst:
        # Using regular expression to find the first word
        first_word_match = re.match(r'\w+', brand)
        if first_word_match:
            first_word = first_word_match.group()
            # Adding "bike" after the first word
            updated_brand = first_word + " bike"
            updated_list.append(updated_brand)
    return updated_list

# Apply the function to the list of bike brands
updated_bike_brands = add_bike_and_remove_after(bike_brands_in_india)

# Print the updated list of bike brands
print(updated_bike_brands)

['Hero bike', 'Bajaj bike', 'TVS bike', 'Royal bike', 'Honda bike', 'Yamaha bike', 'Suzuki bike', 'KTM bike', 'Mahindra bike', 'Jawa bike', 'Benelli bike', 'Harley bike', 'Triumph bike', 'Ducati bike', 'BMW bike', 'Kawasaki bike', 'Husqvarna bike', 'Revolt bike', 'Ather bike']

In [27]:
import pandas as pd

# List of CSV filenames
csv_files = [
    "Ather 450 Apex_bikes.csv",
    "Revolt RV400 BRZ_bikes.csv",
    "Husqvarna Svartpilen 401_bikes.csv",
    "Kawasaki KX65_bikes.csv",
    "BMW K 1600 Bagger_bikes.csv",
    "Ducati DesertX_bikes.csv",
    "Triumph Scrambler 1200 X_bikes.csv",
    "Harley Davidson Road Glide Special_bikes.csv",
    "Benelli Leoncino 500_bikes.csv",
    "Jawa 350_bikes.csv",
    "KTM 390 Adventure X_bikes.csv",
    "Suzuki Katana_bikes.csv",
    "Yamaha FZS 25_bikes.csv",
    "Honda XL750 Transalp_bikes.csv",
    "Royal Enfield Scram 411_bikes.csv",
    "TVS X_bikes.csv",
    "Bajaj Avenger 220 Street_bikes.csv",
    "Hero Destini Prime_bikes.csv"
]

# Create an empty list to store individual DataFrames
dfs = []

# Read each CSV file into a DataFrame and append it to the list
for file in csv_files:
    df = pd.read_csv(file)
    dfs.append(df)

# Concatenate all DataFrames in the list along rows (axis=0)
popular_bike_brands_india_df = pd.concat(dfs, ignore_index=True)

# Now, combined_df contains the data from all CSV files in a single DataFrame

In [16]:
bikes_df_basics = pd.DataFrame(bike_details)

In [17]:
bikes_df_basics

                     Name                   Price                 Basic Specs
0              TVS Raider  Rs.95,219 - 1.03 Lakh*  71.94 kmpl124.8 cc11.38 PS
1      TVS Apache RTR 160    Rs.1.19 - 1.26 Lakh*     47 kmpl159.7 cc16.04 PS
2   TVS Apache RTR 160 4V    Rs.1.24 - 1.45 Lakh*  47.61 kmpl159.7 cc17.55 PS
3           TVS NTORQ 125  Rs.84,636 - 1.05 Lakh*   54.33 kmpl124.8 cc9.38 PS
4               TVS iQube    Rs.1.17 - 1.23 Lakh*                      4.4 kW
5             TVS Jupiter     Rs.73,340 - 89,748*      50 kmpl109.7 cc7.88 PS
6      TVS Apache RTR 310    Rs.2.43 - 2.64 Lakh*    35 kmpl312.12 cc 35.6 PS
7               TVS XL100     Rs.44,999 - 59,695*       80 kmpl99.7 cc4.35 PS
8       TVS Apache RR 310           Rs.2.72 Lakh*     33.1 kmpl312.2 cc 34 PS
9               TVS Ronin    Rs.1.49 - 1.73 Lakh*   42.95 kmpl225.9 cc20.4 PS
10        TVS Jupiter 125     Rs.86,405 - 96,855*   57.27 kmpl124.8 cc8.15 PS
11    TVS Scooty Pep Plus     Rs.65,514 - 68,414*        50 kmpl87.8 cc5.4 PS
12              TVS Sport     Rs.59,431 - 70,773*      70 kmpl109.7 cc8.29 PS
13     TVS Apache RTR 180           Rs.1.32 Lakh*     45 kmpl177.4 cc17.02 PS
14  TVS Apache RTR 200 4V           Rs.1.47 Lakh*    37 kmpl197.75 cc20.82 PS
15             TVS Radeon     Rs.62,405 - 80,744*   73.68 kmpl109.7 cc8.19 PS
16        TVS Scooty Zest     Rs.73,931 - 75,293*      48 kmpl109.7 cc7.81 PS
17     TVS Star City Plus     Rs.78,770 - 81,920*   83.09 kmpl109.7 cc8.19 PS
18                  TVS X           Rs.2.50 Lakh*                    7 kW4 Hr

In [28]:
bike_df1 = bikes_df_basics.copy()

In [37]:
import pandas as pd

# Sample data
data = [
    "71.94 kmpl124.8 cc11.38 PS",
    "47 kmpl159.7 cc16.04 PS",
    "47.61 kmpl159.7 cc17.55 PS",
    "54.33 kmpl124.8 cc9.38 PS",
    "4.4 kW",
    "50 kmpl109.7 cc7.88 PS",
    "35 kmpl312.12 cc 35.6 PS",
    "80 kmpl99.7 cc4.35 PS",
    "33.1 kmpl312.2 cc 34 PS",
    "42.95 kmpl225.9 cc20.4 PS",
    "57.27 kmpl124.8 cc8.15 PS",
    "50 kmpl87.8 cc5.4 PS",
    "70 kmpl109.7 cc8.29 PS",
    "45 kmpl177.4 cc17.02 PS",
    "37 kmpl197.75 cc20.82 PS",
    "73.68 kmpl109.7 cc8.19 PS",
    "48 kmpl109.7 cc7.81 PS",
    "83.09 kmpl109.7 cc8.19 PS",
    "7 kW4 Hr"
]

# Regular expression pattern to extract numerical values
pattern = r'(\d+(?:\.\d+)?)'

# Extracting numerical values using regex
extracted_data = pd.Series(data).str.extractall(pattern)

# Convert the extracted numerical values to a single series
numerical_values = extracted_data[0].groupby(level=0).agg(' '.join)

# Split the numerical values into separate columns
numerical_values = numerical_values.str.split(expand=True)

# Rename columns
numerical_values.columns = ["Mileage (Kmpl) ", "Displacement (cc)", "Power (ps)"]

# Display the DataFrame
print(numerical_values)

pd.DataFrame(numerical_values)

   Mileage (Kmpl)  Displacement (cc) Power (ps)
0            71.94             124.8      11.38
1               47             159.7      16.04
2            47.61             159.7      17.55
3            54.33             124.8       9.38
4              4.4              None       None
5               50             109.7       7.88
6               35            312.12       35.6
7               80              99.7       4.35
8             33.1             312.2         34
9            42.95             225.9       20.4
10           57.27             124.8       8.15
11              50              87.8        5.4
12              70             109.7       8.29
13              45             177.4      17.02
14              37            197.75      20.82
15           73.68             109.7       8.19
16              48             109.7       7.81
17           83.09             109.7       8.19
18               7                 4       None

In [38]:
df2 = pd.DataFrame(numerical_values)

In [40]:
merged_df = pd.concat([bike_df1, df2], axis=1)

In [43]:
merged_df.drop('Basic Specs',axis = 1)

,Name,Price,Mileage (Kmpl),Displacement (cc),Power (ps)
0,TVS Raider,"Rs.95,219 - 1.03 Lakh*",71.94,124.8,11.38
1,TVS Apache RTR 160,Rs.1.19 - 1.26 Lakh*,47,159.7,16.04
2,TVS Apache RTR 160 4V,Rs.1.24 - 1.45 Lakh*,47.61,159.7,17.55
3,TVS NTORQ 125,"Rs.84,636 - 1.05 Lakh*",54.33,124.8,9.38
4,TVS iQube,Rs.1.17 - 1.23 Lakh*,4.4,None,None
5,TVS Jupiter,"Rs.73,340 - 89,748*",50,109.7,7.88
6,TVS Apache RTR 310,Rs.2.43 - 2.64 Lakh*,35,312.12,35.6
7,TVS XL100,"Rs.44,999 - 59,695*",80,99.7,4.35
8,TVS Apache RR 310,Rs.2.72 Lakh*,33.1,312.2,34
9,TVS Ronin,Rs.1.49 - 1.73 Lakh*,42.95,225.9,20.4
10,TVS Jupiter 125,"Rs.86,405 - 96,855*",57.27,124.8,8.15
11,TVS Scooty Pep Plus,"Rs.65,514 - 68,414*",50,87.8,5.4
12,TVS Sport,"Rs.59,431 - 70,773*",70,109.7,8.29
13,TVS Apache RTR 180,Rs.1.32 Lakh*,45,177.4,17.02
14,TVS Apache RTR 200 4V,Rs.1.47 Lakh*,37,197.75,20.82
15,TVS Radeon,"Rs.62,405 - 80,744*",73.68,109.7,8.19
16,TVS Scooty Zest,"Rs.73,931 - 75,293*",48,109.7,7.81
17,TVS Star City Plus,"Rs.78,770 - 81,920*",83.09,109.7,8.19
18,TVS X,Rs.2.50 Lakh*,7,4,None